import {
  db,
  Pets,
  AdoptionRequestsDB,
  CreditCardsDB,
  UserAuth,
} from "astro:db";
import { v4 as uuidv4 } from "uuid";
import bcrypt from "bcrypt";
export default async function () {
  await db.insert(Pets).values([
    {
      id: "311221",
      petname: "Maykelbb",
      age: 3,
      gender: "macho",
      species: "gato",
      img: "https://th.bing.com/th/id/OIP.DZxGvmQNRyqBpiFYR74KdQHaEK?rs=1&pid=ImgDetMain",
      fileId: "gggg",
    },
    {
      id: "999",
      petname: "Paco",
      age: 4,
      gender: "macho",
      species: "perro",
      img: "https://th.bing.com/th/id/OIP.DZxGvmQNRyqBpiFYR74KdQHaEK?rs=1&pid=ImgDetMain",
      fileId: "ggg3g",
    },
      {
      id: uuidv4(),
      petname: "Jacinto",
      age: 2.5,
      gender: "macho",
      species: "perro",
      img: "https://th.bing.com/th/id/OIP.DZxGvmQNRyqBpiFYR74KdQHaEK?rs=1&pid=ImgDetMain",
      fileId: "gggg",
    },
  ]);
  await db.insert(AdoptionRequestsDB).values([
    {
      id: uuidv4(),
      fullname: "Rosanne Vazquez Nunez",
      age: 21,
      cellPhone: 56775245,
      alternativeCellPhone: 56775245,
      address: "Playa, Jaimanistas",
      motivation: "Me gusta animales",
      forWho: "Para mi",
      petMoney: "Si",
      petFollowing: "Si",
      notAbandoned: "Si",
      ownHouse: "Alquilado",
      agreeRent: "Si",
      bigPlace: "Si",
      sleepPlace: "Camita de perro",
      houseNotScape: "Si",
      childrens: "No",
      petAlergic: "No",
      family: "mi novio",
      adoptionAgree: "Si",
      howManyPets: 0,
      petsBefore: "Si",
      petsBeforeAlive: "Si",
      job: "Trabajo",
      iftravel: "Si",
      petIfTravel: "Mi mm lo cuidara",
      otherHouse: "Si",
      petDoctorClose: "Para mi",
      vacunationSchema: "Para mi",
      sterilizationOpinion: "Bien",
      youAgree: "Si",
      CImgFront: "https://th.bing.com/th/id/OIP.uji87jJr-E5MppjfnrVCdwHaDt?rs=1&pid=ImgDetMain",
      CImgBack: "https://th.bing.com/th/id/OIP.uji87jJr-E5MppjfnrVCdwHaDt?rs=1&pid=ImgDetMain",
      idImgCIFront: "gggg",
      idImgCBack: "ggg3g",
      petId: "311221",
      isRead: false,
      isApproved: false,
    },
    {
      id: uuidv4(),
      fullname: "Erick Garcia",
      age: 23,
      cellPhone: 56775245,
      alternativeCellPhone: 56775245,
      address: "La Lisa, UCI",
      motivation: "Me gusta animales",
      forWho: "Para mi",
      petMoney: "Si",
      petFollowing: "Si",
      notAbandoned: "Si",
      ownHouse: "Alquilado",
      agreeRent: "Si",
      bigPlace: "Si",
      sleepPlace: "Camita de perro",
      houseNotScape: "Si",
      childrens: "No",
      petAlergic: "No",
      family: "mi novio",
      adoptionAgree: "Si",
      howManyPets: 0,
      petsBefore: "Si",
      petsBeforeAlive: "Si",
      job: "Trabajo",
      iftravel: "Si",
      petIfTravel: "Mi mm lo cuidara",
      otherHouse: "Si",
      petDoctorClose: "Para mi",
      vacunationSchema: "Para mi",
      sterilizationOpinion: "Bien",
      youAgree: "Si",
      CImgFront: "https://images.unsplash.com/photo-1678489860935-a5a732d25b4d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
      CImgBack: "https://images.unsplash.com/photo-1678489860935-a5a732d25b4d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
      idImgCIFront: "ggg3g",
      idImgCBack: "gggg",
      petId: "999",
      isRead: false,
      isApproved: false,
    },
  ]);

  await db.insert(CreditCardsDB).values([
    {
      id: uuidv4(),
      cardNumber: "9254-0987-5643-6543",
      numberPhone: 56775245,
      nameCard: "Tarjeta de prueba",
    },
    {
      id: uuidv4(),
      cardNumber: "9254-6621-5643-8734",
      numberPhone: 58908790,
      nameCard: "Tarjeta de prueba",
    },
    {
      id: uuidv4(),
      cardNumber: "1234-0987-5643-6543",
      numberPhone: 53435687,
      nameCard: "Tarjeta de prueba",
    },
  ]);

  await db.insert(UserAuth).values([
    {
      id: uuidv4(),
      username: "rosanne",
      password: bcrypt.hashSync("123456", 10),
    },
  ]);
}
