import { db, Pets, AdoptionRequestsDB, CreditCardsDB } from "astro:db";
import { v4 as uuidv4 } from "uuid";
export default async function () {
  await db.insert(Pets).values([
    {
      id: "311221",
      petname: "Maykelbb",
      age: 3,
      gender: "macho",
      species: "gato",
    },
    {
      id: "999",
      petname: "Paco",
      age: 4,
      gender: "macho",
      species: "perro",
    },
    { id: uuidv4(), petname: "Juan", age: 1, gender: "macho", species: "gato" },
    {
      id: uuidv4(),
      petname: "Manolo",
      age: 5,
      gender: "macho",
      species: "perro",
    },
    { id: uuidv4(), petname: "Max", age: 4, gender: "macho", species: "perro" },
    {
      id: uuidv4(),
      petname: "Maria",
      age: 3,
      gender: "hembra",
      species: "gato",
    },
    {
      id: uuidv4(),
      petname: "Roberto",
      age: 1,
      gender: "macho",
      species: "gato",
    },
    {
      id: uuidv4(),
      petname: "Juana",
      age: 5,
      gender: "hembra",
      species: "perro",
    },
    {
      id: uuidv4(),
      petname: "Pedro",
      age: 4,
      gender: "macho",
      species: "perro",
    },
    {
      id: uuidv4(),
      petname: "Julia",
      age: 3,
      gender: "hembra",
      species: "gato",
    },
    {
      id: uuidv4(),
      petname: "Carlos",
      age: 1,
      gender: "macho",
      species: "gato",
    },
    {
      id: uuidv4(),
      petname: "Ana",
      age: 5,
      gender: "hembra",
      species: "perro",
    },
  ]);
  await db.insert(AdoptionRequestsDB).values([
    {
      id: uuidv4(),
      fullname: "Rosanne Vazquez Nunez",
      age: 21,
      cellPhone: 56775245,
      alternativeCellPhone: 56775245,
      address: "Playa, Jaimanistas",
      motivation: "Me gusta animales",
      forWho: "Para mi",
      petMoney: "Si",
      petFollowing: "Si",
      notAbandoned: "Si",
      ownHouse: "Alquilado",
      agreeRent: "Si",
      bigPlace: "Si",
      sleepPlace: "Camita de perro",
      houseNotScape: "Si",
      childrens: "No",
      petAlergic: "No",
      family: "mi novio",
      adoptionAgree: "Si",
      howManyPets: 0,
      petsBefore: "Si",
      petsBeforeAlive: "Si",
      job: "Trabajo",
      iftravel: "Si",
      petIfTravel: "Mi mm lo cuidara",
      otherHouse: "Si",
      petDoctorClose: "Para mi",
      vacunationSchema: "Para mi",
      sterilizationOpinion: "Bien",
      youAgree: "Si",
      petId: "311221",
      isRead: false,
      isApproved: false,
    },
    {
      id: uuidv4(),
      fullname: "Erick Garcia",
      age: 23,
      cellPhone: 56775245,
      alternativeCellPhone: 56775245,
      address: "La Lisa, UCI",
      motivation: "Me gusta animales",
      forWho: "Para mi",
      petMoney: "Si",
      petFollowing: "Si",
      notAbandoned: "Si",
      ownHouse: "Alquilado",
      agreeRent: "Si",
      bigPlace: "Si",
      sleepPlace: "Camita de perro",
      houseNotScape: "Si",
      childrens: "No",
      petAlergic: "No",
      family: "mi novio",
      adoptionAgree: "Si",
      howManyPets: 0,
      petsBefore: "Si",
      petsBeforeAlive: "Si",
      job: "Trabajo",
      iftravel: "Si",
      petIfTravel: "Mi mm lo cuidara",
      otherHouse: "Si",
      petDoctorClose: "Para mi",
      vacunationSchema: "Para mi",
      sterilizationOpinion: "Bien",
      youAgree: "Si",
      petId: "999",
      isRead: false,
      isApproved: false,
    },
  ]);

  await db.insert(CreditCardsDB).values([
    {id: uuidv4(), cardNumber: "9254-0987-5643-6543", numberPhone: 56775245},
    {id: uuidv4(), cardNumber: "9254-6621-5643-8734", numberPhone: 58908790},
    {id: uuidv4(), cardNumber: "1234-0987-5643-6543", numberPhone: 53435687},
  ])
}
